name = "AllocationOpt"
uuid = "e2472b13-1eb9-46f1-ac4b-64ea04136a8a"
authors = ["The Graph Foundation"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Formatting = "59287772-0a20-5a39-b81b-1366585eb4c0"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Mocking = "78c3b35d-d492-501b-9361-3d52fe80e533"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
SemioticOpt = "a0c0fc10-8635-40d2-82ff-39f738735ee1"
SplitApplyCombine = "03a91e81-4c3e-53e1-a0a4-9c0c8f19dd66"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
TheGraphData = "871720c8-5dfb-4fa2-998e-3fe6ebd08819"
TypedTables = "9d95f2ec-7b3d-5a63-8d20-e2491e220bb9"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
