name = "AllocationOpt"
uuid = "c8d4fa36-652a-4cad-a59b-8b946e6f88a6"
authors = ["The Graph Foundation"]
version = "1.0.1"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
GraphQLClient = "09d831e3-9c21-47a9-bfd8-076871817219"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"

[compat]
CSV = "0.10"
DataFrames = "1"
GraphQLClient = "0.7"
Revise = "3"
Roots = "1"
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
