name = "AllocationOpt"
uuid = "c8d4fa36-652a-4cad-a59b-8b946e6f88a6"
authors = ["The Graph Foundation"]
version = "1.5.0"

[deps]
Debugger = "31a5f54b-26ea-5ae9-a837-f05ce5417438"
Formatting = "59287772-0a20-5a39-b81b-1366585eb4c0"
GraphQLClient = "09d831e3-9c21-47a9-bfd8-076871817219"
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"

[compat]
GraphQLClient = "0.7"
Revise = "3"
Roots = "1, 2"
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
